"""empty message

Revision ID: 9bb76979c949
Revises: 9f3b78c5b796
Create Date: 2018-09-09 22:35:59.054758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb76979c949'
down_revision = '9f3b78c5b796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_img', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_img')
    # ### end Alembic commands ###
