"""empty message

Revision ID: 9f3b78c5b796
Revises: e57641823a28
Create Date: 2018-09-09 22:35:10.362317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3b78c5b796'
down_revision = 'e57641823a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_img', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
